import './globals.css';
import Menu from './components/menu/menu';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Menu />
        <h1>Flux capacitors R us</h1>
        {children}
      </body>
    </html>
  );
}
